import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export interface Tag {
  id: number;
  label: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Article {
  id: number;
  title: string;
  text: string;
  createdAt: Date;
  updatedAt: Date;
  tags: Tag[];
}

export default function Home() {
  const [articles, setArticles] = useState<Article[]>([]);
  const getArticles = async () => {
    const articles = await (
      await fetch("http://13.231.5.6:4000/articles")
    ).json();
    console.log("articles", articles);
    setArticles(articles);
    return articles;
  };

  useEffect(() => {
    getArticles();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {articles.map((article) => {
          return <p>{article.title}</p>;
        })}
      </main>
    </>
  );
}
