import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Articles } from "../domain/repositories";
import { Article } from "../domain/models";

export default function Home() {
  const [articles, setArticles] = useState<Article.Model[]>([]);
  const getArticles = async () => {
    const articles = await Articles.getALl();
    setArticles(articles);
    return articles;
  };

  useEffect(() => {
    getArticles();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          <Link href="/article/new">記事を作成</Link>
        </p>
        <p>
          <Link href="/tag/new">タグを追加</Link>
        </p>
        {articles.map((article) => {
          return (
            <div key={article.id} style={{ marginBottom: 20 }}>
              <p>
                <Link href={`/article/${article.id}`}>{article.title}</Link>
              </p>
            </div>
          );
        })}
      </main>
    </>
  );
}
