import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const getArticles = async () => {
    const articles = await (
      await fetch("http://13.231.5.6:4000/articles")
    ).json();
    console.log("articles", articles);
    return articles;
  };

  useEffect(() => {
    getArticles();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>ああああああ</p>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div></div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}></div>
        </div>
      </main>
    </>
  );
}
